#%RAML 1.0
---

title: Calculation Service
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/calculation

documentation:
  - title: Overview
    content: !include docs/overview.md

mediaType: [ application/json ]

/calculate:
  post:
    displayName: Submit Calculation
    description: This resource returns a calculation based on a set of submitted items. The endpoint returns a list of allowances and a calculation of the duties due on all of the items that are above the user's allowances
    body:
      application/json:
        type: !include schemas/calculateRequest.json
        example: !include examples/calculateRequestExample.json
        responses:
          200:
            body:
              application/json:
                type: !include schemas/calculateResponse.json
                example: !include examples/calculateResponseExample.json

/products:
  get:
    displayName: Get Products
    description: This resource returns Products data
    responses:
      200:
        body:
          application/json:
            type: !include schemas/productsResponse.json
            example: !include examples/productsResponseExample.json
/countries:
  get:
    displayName: Get Countries
    description: This resource returns Countries data
    responses:
      200:
        body:
          application/json:
            type: !include schemas/countriesResponse.json
            example: !include examples/countriesResponseExample.json
/currencies:
  get:
    displayName: Get Currencies
    description: This resource returns Currencies data
    responses:
      200:
        body:
          application/json:
            type: !include schemas/currenciesResponse.json
            example: !include examples/currenciesResponseExample.json
/allowances:
  get:
    displayName: Get Allowances
    description: This resource returns EU and ROW allowances data
    responses:
      200:
        body:
          application/json:
            type: !include schemas/allowancesResponse.json
            example: !include examples/allowancesResponseExample.json
/cigaretterrps:
  get:
    displayName: Get Cigarette Recommended Retail Prices
    description: This resource returns Recommended Retail Price data for cigarettes
    responses:
      200:
        body:
          application/json:
            type: !include schemas/cigaretterrpsResponse.json
            example: !include examples/cigaretterrpsResponseExample.json

